{{- if  .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mariadb-enterprise-operator.fullname" . }}
  labels:
    {{ include "mariadb-enterprise-operator.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{ include "mariadb-enterprise-operator.selectorLabels" . | nindent 6 }}
{{- end }}
