{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled .Values.webhook.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mariadb-enterprise-operator.fullname" . }}-webhook
  labels:
    {{ include "mariadb-enterprise-operator-webhook.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.webhook.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{ include "mariadb-enterprise-operator-webhook.selectorLabels" . | nindent 6 }}
{{- end }}
