{{- if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-enterprise-operator.fullname" . }}-webhook
  labels:
    {{- include "mariadb-enterprise-operator-webhook.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "mariadb-enterprise-operator-webhook.selectorLabels" . | nindent 4 }}
{{- end }}