{{- if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mariadb-enterprise-operator-webhook.serviceAccountName" . }}
  labels:
    {{- include "mariadb-enterprise-operator-webhook.labels" . | nindent 4 }}
    {{- with .Values.webhook.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}