{{- if and (not .Values.currentNamespaceOnly) .Values.certController.enabled (not .Values.webhook.cert.certManager.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mariadb-enterprise-operator-cert-controller.serviceAccountName" . }}-cert-controller
  labels:
    {{- include "mariadb-enterprise-operator-cert-controller.labels" . | nindent 4 }}
    {{- with .Values.certController.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.certController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}