apiVersion: v2
name: mariadb-enterprise-operator-crds
description: MariaDB Enterprise Operator CRDs
home: https://github.com/mariadb-corporation/mariadb-enterprise-operator-helm
icon: https://operator.mariadb.com/assets/mariadb_profile.svg
type: application
version: 25.8.0
appVersion: "0.0.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - email: operator@mariadb.com
    name: MariaDB Corporation
  - email: support@mariadb.com
    name: Support
  - email: sales-EMEA@mariadb.com
    name: Sales EMEA
  - email: sales-APAC@mariadb.com
    name: Sales APAC
  - email: sales-nam@mariadb.com
    name: Sales Americas
keywords:
  - mariadb
  - mysql
  - operator
  - mariadb-enterprise-operator
  - database
  - maxscale
